# Generated by Django 4.2.5 on 2023-10-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='back_half',
            field=models.SlugField(unique=True),
        ),
    ]
