# Generated by Django 4.2.5 on 2023-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_alter_short_back_half'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='short',
            name='foreground_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
