# Generated by Django 4.2.5 on 2023-11-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_short_background_color_short_foreground_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='custom_back_half',
            field=models.BooleanField(default=False),
        ),
    ]
